kind: pipeline
trigger:
  event:
    - cron
    - push
  branch:
    - master

environment:
  BASE_REPO_API: https://api.github.com/repos/cenk1cenk2/softether-vpnsrv/releases/latest
  TRACK_REPO_API: https://api.github.com/repos/SoftEtherVPN/SoftEtherVPN/releases/latest

name: publish
steps:
  - name: check-version
    image: alpine/git:latest
    commands:
      - apk add curl --no-cache --no-progress
      - export BASE_RELEASE=$(curl --silent $BASE_REPO_API | grep "tag_name" | sed -r 's/.*(".*").*"(.*)".*/\2/g')
      - export TRACK_RELEASE=$(curl --silent $TRACK_REPO_API | grep "tag_name" | sed -r 's/.*(".*").*"(.*)".*/\2/g')
      - 'echo "Repository last tag: $BASE_RELEASE"'
      - 'echo "Tracking last tag: v$TRACK_RELEASE"'
      - git config --global --add url."https://$GITHUB_USERNAME:$GITHUB_DEPLOY_TOKEN@github.com/".insteadOf "https://github.com/"
      - 'if [ "$BASE_RELEASE" != "v$TRACK_RELEASE" ]; then git tag v$TRACK_RELEASE && git push origin v$TRACK_RELEASE; fi'
    environment:
      GITHUB_USERNAME:
        from_secret: github_username
      GITHUB_DEPLOY_TOKEN:
        from_secret: github_deploy_token
    when:
      event:
        - cron
        - push
      branch:
        - master
#
  - name: publish
    image: plugins/docker
    working_dir: /build
    settings:
      repo: cenk1cenk2/softether-vpnsrv
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      tag:
        - latest
        - ${DRONE_TAG}
    when:
      event:
        - tag
      branch:
        - master
